package Locators;

import org.openqa.selenium.By;

public class ProvisioningPom {

    public static By provisioningButton = By.xpath("//p[text()='Provisioning']");
    public static By searchApps = By.xpath("//input[@class='Search-module_searchInput__NDheI text-md-regular']");
    public static By Description = By.xpath("//textarea[@name='description']");
    public static By SpDomain = By.xpath("//input[@name='spDomain']");
    public static By authorizationType = By.xpath("(//input[@id='select-select-field'])[2]");
    public static By selectAuthorizationtype = By.xpath("//span[@class='Select-module_option-label__DTNS2']");
    public static By tokenType = By.xpath("(//div[@class='Select-module_custom-select-container__jhtOF   w-full'])[3]/input");
    public static By selectTokenType = By.xpath("//span[@class='Select-module_option-label__DTNS2']");
    public static By nextButton = By.xpath("//button[text()='Next']");
    public static By serviceToken = By.xpath("//textarea[@placeholder='Enter service token']");
    public static By apiEndpointUrl = By.xpath("//input[@name='tokenApiEndpoint']");
    public static By administratorEmail = By.xpath("//input[@placeholder='Enter administrator username or email']");
    public static By apiTokenUsername = By.xpath("//input[@placeholder='Enter username or email']");
    public static By scope = By.xpath("//input[@placeholder='Enter Scope']");
    public static By testButton = By.xpath("//button[text()='Test']");
    public static By addScope = By.xpath("//div[@class='flex pt-2 gap-2']/button[@class='Button-module_button__18Bed Button-module_contained__B-47X Button-module_primary__st6yY Button-module_iconOnly__FNrSu Button-module_responsive__wGjrI text-sm-semibold action-btn']");
    public static By done = By.xpath("//button[text()='Done']");
    public static By provisioningApiEndpoint = By.xpath("//input[@name='apiEndpointUrl']");
    public static By provisioningMethodType = By.xpath("//div[@class='Select-module_custom-select-container__jhtOF   w-full']");
    public static By provisioningSelectMethodType = By.xpath("//div[@class='Select-module_custom-select-option__4BfXL ']");
    public static By provisioningRequestPayload = By.xpath("//textarea[@name='requestPayload']");
    public static By provisioningResponsePayload = By.xpath("//textarea[@name='sampleResponse']");
    public static By provisionResponseAttrbuteMapping = By.xpath("//input[@class= 'TextField-module_field-input__XxGyf   w-full   undefined']");
    public static By getRoleApiEndpoint = By.xpath("//input[@name ='getRole.apiEndpointUrl']");
    public static By getroleMethodType = By.xpath("(//div[@class='Select-module_custom-select-container__jhtOF   w-full'])[1]/input");
    public static By getroleSelectMethodType = By.xpath("(//div[@class='Select-module_custom-select-option__4BfXL '])[position()=1 or position()=2]");
    public static By getroleResponsePayload = By.xpath("//textarea[@name='getRole.sampleResponse']");
    public static By getroleResponseAttributeMapping = By.xpath("//input[@class='TextField-module_field-input__XxGyf   w-full   undefined']");
    public static By assignRoleApiEndpoint = By.xpath("//input[@name='assignRole.apiEndpointUrl']");
    public static By assignroleMethodType = By.xpath("(//div[@class='Select-module_custom-select-container__jhtOF   w-full'])[2]/input");
    public static By assignroleSelectMethodType = By.xpath("(//div[@class='Select-module_custom-select-option__4BfXL '])");
    public static By assignroleRequestPayload = By.xpath("//textarea[@name='assignRole.requestPayload']");
    public static By assignroleResponsePayload = By.xpath("//textarea[@name='assignRole.sampleResponse']");
    public static By assignroleResponseAttributeMapping = By.xpath("//input[@placeholder='e.g., id or username']");
    public static By assignroleaddButtonResponseAttribute = By.xpath("(//span[@class='Button-module_icon__xIuVv'])[3]");
    public static By getGroupApiEndpoint = By.xpath("//input[@name='getGroup.apiEndpointUrl']");
    public static By getGroupMethodType = By.xpath("(//div[@class='Select-module_custom-select-container__jhtOF   w-full'])[1]/input");
    public static By getGroupSelectMethodType = By.xpath("(//div[@class='Select-module_custom-select-option__4BfXL '])[position()=1 or position()=2]");
    public static By getGroupResponsePayload = By.xpath("//textarea[@name='getGroup.sampleResponse']");
    public static By getGroupResponseAttributeMapping = By.xpath("//div[@class='TextField-module_wrapper__wzHwV']/div/input");
    public static By assignGroupApiEndpoint = By.xpath("//input[@name='assignGroup.apiEndpointUrl']");
    public static By assignGroupMethodType = By.xpath("(//div[@class='Select-module_custom-select-container__jhtOF   w-full'])[2]/input");
    public static By assignGroupSelectMethodType = By.xpath("(//div[@class='Select-module_custom-select-option__4BfXL '])");
    public static By assignGroupRequestPayload = By.xpath("//textarea[@name='assignGroup.requestPayload']");
    public static By assignGroupResponsePayload = By.xpath("//textarea[@name='assignGroup.sampleResponse']");
    public static By assignGroupResponseAttributeMapping = By.xpath("//input[@placeholder='e.g., id or username']");
    public static By assignGroupPathVariable = By.xpath("//input[@name='assignGroup.pathVariable[0].key']");
    public static By DeprovisionPathVariable = By.xpath("//input[@class='TextField-module_field-input__XxGyf   w-full   undefined']");
    public static By groupdeprovisionPathVariableAdd = By.xpath("(//span[@class='Button-module_icon__xIuVv'])[2]");
    public static By browseFromConnector = By.xpath("//button[text()='Select']");
    public static By akkuConnector = By.xpath("//p[@class='text-md-bold text-secondary']");
    public static By connectorAddButton = By.xpath("//button[text()='Add Connector']");
    public static By sourceandtargetAttributedropdown = By.xpath("//input[@class='Select-module_custom-select-input__2SwNw ']");
    public static By sourceandtargetAttributedropdown2 = By.xpath("//input[@type='text']");
    public static By selectAttribute = By.xpath("//div[@class='Select-module_custom-select-option__4BfXL ']");
    public static By attributeaddButton = By.xpath("//span[@class='Button-module_icon__xIuVv']");
    public static By skipButton = By.xpath("//button[text()='Skip']");
    public static By confirmButton = By.xpath("//button[text()='Confirm']");
    public static By provisionActiveInactiveToggle1 = By.xpath("//button[text()='Enable Provisioning']");
    public static By provisionActiveInactiveToggle2 = By.xpath("//button[text()='Disable Provisioning']");
    public static By provisionDeactivateMessage = By.xpath("//div[text()='Provisioning engine deactivated successfully.']");
    public static By provisionActivateMessage = By.xpath("//div[text()='Provisioning engine activated successfully.']");
    public static By deleteButton = By.xpath("//Span[text()='Delete']");
    public static By provisionDeleteMessage = By.xpath("//div[text()='Provisioning engine deleted successfully.']");
    public static By deleteYesButton = By.xpath("//button[text()='Yes']");
    public static By apiToken = By.xpath("//textarea[@name='apiToken']");
    public static By tokenMethodType = By.xpath("//div[@class='Select-module_custom-select-container__jhtOF   w-full']");
    public static By assignGroupRequestVariable = By.xpath("(//div[@class='flex flex-col w-full mt-4'])[3]/div/div/div/input");
    public static By deprovisionRequestVariable = By.xpath("(//div[@class='min-w-[49%]'])/div/div/input");
    public static By groupdeprovisionRequestVariableAdd = By.xpath("(//span[@class='Button-module_icon__xIuVv'])[1]");
    public static By provisioningConnectorCompleteMessage = By.xpath("//p[text()='Provisioning configuration completed successfully.']");
    public static By provisionPublishMessage = By.xpath("//div[text()='Provisioning engine published successfully.']");
    public static By requestAccess = By.xpath("//button[text()='Request Access']");
    public static By requestSubmitted = By.xpath("//p[text()='Provisioning access request submitted. You’ll be notified via email once reviewed.']");
    public static By pendingRequest = By.xpath("//div[text()='Access Requests']");
    public static By approve = By.xpath("//span[text()='Approve']");
    public static By paginationNew = By.xpath("(//a[@rel='nofollow'])[position() > 1]");
    public static By approveRequestMessage = By.xpath("//p[text()='The provisioning access request has been approved successfully.']");
    public static By requestTemporaryAccess = By.xpath("//button[text()='Request Temporary Access']");
    public static By startDate = By.name("startDate");
    public static By endDate = By.name("endDate");
    public static By sendButton = By.xpath("//span[text()='Send']");
    public static By reject = By.xpath("//span[text()='Reject']");
    public static By rejectRequestMessage = By.xpath("//p[text()='The provisioning access request has been rejected successfully.']");
    public static By allApps = By.xpath("//div[text()='All Apps']");

}
